[build]
  command = "npx expo export -p web"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[dev]
  command = "npx expo start --web"
  targetPort = 8081
  port = 8888

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
